.travis.yml
package.json

Use a date-time stamp for the patch version. It'll make it easier to know when translations have been updated (the most common type of release)
Bump major version to 1.0 to start using this in scratch-gui.

Npm versioning

---

.npmignore
package.json

Need the built artifacts to use it. Was trying to decide between `prepublishOnly` and `prepare` (see https://docs.npmjs.com/misc/scripts#prepublish-and-prepare). prepublishOnly looks like the correct solution as the packages needed to build are all just dev dependencies.

Build all the data before publishing

---

.tx/config
package.json
paint/ar.json
paint/de.json
paint/en.json
paint/es.json
paint/he.json
scripts/build-data.js
src/index.js
src/supported-locales.js

Breaking change - bumped major version to 2.
Restructured to support multiple components. Package default is just localeData for currently supported locales including the name for each language.
messages for each component are exported as separate files in locales. Clients of l10n will need to import messages for each of the compents used and combine them.

Add scratch-paint

---

package.json

- Use src/index for browser entry point instead of webpack build library
- Depend on dependencies used in `src` as non-dev dependencies
- Build node version with non-dev dependencies as external modules
Sibling of https://github.com/LLK/scratch-vm/pull/1106

Use src/index as browser entry point

---

LICENSE
TRADEMARK

I'm assuming that the default files from gui are appropriate for scratch-l10n.

Include default Scratch License and TM files

---

scripts/build-data.js

Scratch-blocks includes the blocks messages. Excluding them from the editor-msgs file will save >500kb
This repo publishes a messages file that combines all the messages so gui only has to import one file. However, scratch-blocks needs it's own messages so currently the blocks translations are getting included twice (via l10n, and as the scratch-msgs.js file in scratch-blocks).

Exclude blocks messages from the combined file

---

scripts/tx-util.js

The placeholder checking didn’t work if the translation’s grammar generated a different number of parsed elements.
E.g., in English:
something {placeholder} — two elements
translation
something {placeholder} something — three elements
I determined that placeholders are always array elements in the parsed array, so filter for Array elements and check that there are the same number of array elements.

Fix placeholder checking

---

.travis.yml

Created a slack integration that posts to the scratch-ops channel and added the token as ENV variable in travis.
Configured the slack notification to only post on failure.

Add l10n build failure notification to slack

---

src/index.js
src/supported-locales.js

as of react-intl 2.8.0 māori (mi) locale data is included in `react-intl/locale-data`. Use that instead of a custom locale.
Also remove unnecessary `es-419` custom locale, `es-419` is already included in the default `es.js` locale-data.

import māori locale-data

---

src/supported-locales.js

It should match other languages
Belarusian translator messaged me in transifex and provided a new string with the name capitalized.

Capitalize Belarusian in language menu

---

.circleci/config.yml

The jobs that don’t run the build and test job (scheduled jobs) need to install the node modules because they’re not already in the workspace. The `node/install-packages` command from the node orb will use cached modules if available.

install node-modules for cron workflows

---

.circleci/config.yml

Run the cron jobs in the early morning instead of later in the evening.
* 3am should allow enough time for the weekly translations to get merged up to www

Revise Cron job schedule

---

.circleci/config.yml

Change the frequency of the job that pulls translations for the editor and www so that the staging server translations are updated more often, and we know earlier if there are translation problems.
Clarify that the time in the cron jobs is UTC, not local.
- Resolves #126 
Changes the schedule for the circle-ci cron job and clarifies that the time is UTC, not local.
No update of translations in this PR.

Update circle-ci config to pull translations daily

---

package-lock.json
scripts/tx-push-src.js

- Resolves #128 
When trying to update a resource on transifex, it catches the file not found response and tries to create it instead.
This required adding a function that will return the correct file type for the resource based on the repository. Note, it will fail for new repositories. Also switched to using process.exitCode instead of process.exit to give async calls opportunity to finish.
Also checking in package lock changes, although they appear to be just changing. `http` to `https`
I linked my local copy of www (develop branch) to the new version of l10n, then ran `npm run i18n:push`. The www script runs `tx-push-src` for all l10n files in www. Here's the output. Note that annual-report got the message about creating the resource instead of a 404 error:
```
$ npm run i18n:push
> …
```

Modify push script to create non-existent resource

---

src/supported-locales.js

- Resolves #142 
Renames the entry for Spanish to indicate that it's the Spain version of Spanish.

Rename 'Español' to 'Español (España)'

---

lib/transifex.js
scripts/tx-push-src.js

- Resolves #171 and CE-180
This PR is a rebased version of #162, modifying the `tx-push-src` script to use the Transifex v3 API. There should be no breaking API changes introduced in this PR, and it has been tested from within `scratch-www` and seems to work as expected.
The scripts for pushing and pulling help article strings will be migrated to the new API in a followup PR (#176).

CE-180: Push source strings with Transifex v3 API

---

lib/transifex.js
scripts/help-utils.js
scripts/tx-push-help.js

- Resolves #171 and CE-180
This PR is a followup to #175 which updates the help string utils to use the v3 transifex API helper functions introduced in that PR. This PR also adds some new helper functions, `txResourcesObjects` and `txAvailableLanguages` to maintain identical functionality to the v2 API help string utils. The only new commits in this PR are 58a408e6663ff03e0f4d5903759021c7413e2d08 and d39eddebc2930765c18c4f5883ba40c4bae73b45.

WIP CE-180: push help article strings

---

lib/transifex.js

- the `sync-help` job on circleci was always failing with an `Error: Cannot read properties of null (reading 'map') error`, which it turns out was a result of `txAvailableLanguages` not returning anything. The cause of this was that the transifex v3 api apparently requires you to run `.fetch()` on the object that's returned from `project.fetch('languages')`.
- runs `languages.fetch()` before getting language codes
- gets language code with `l.attributes.code` instead of `l.code`

Fix txAvailableLanguages

---

.github/workflows/ci-cd.yml
.github/workflows/daily-tx-pull.yml

Run the CI/CD workflow after the daily TX update, but only if changes were made.
Under CCI, if the daily TX update pushed a commit, that push would trigger a regular build and release. Under GHA, one workflow's actions are normally prevented from triggering another workflow (see [here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow)). This means that, after GHA migration, the daily TX update would make a commit but that commit was not being released. This change fixes that, so the `scratch-l10n` module on NPM will once again automatically stay up to date with changes made on TX.
Since this relies on interaction between the workflows and there are not currently any changes ready on TX, I have not fully tested the …

Release after TX commit

---

.github/workflows/ci-cd.yml
.github/workflows/commitlint.yml
.github/workflows/daily-tx-pull.yml

- Attempt #185 again, using a step output parameter this time
- In #185, this used an outdated syntax for setting an environment variable. That syntax is [deprecated and blocked by default](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), so it didn't work.
- This PR uses a step output parameter instead.
- This could have been solved by using `echo STUFF >> "$GITHUB_ENV"` but I think using a step output is even better, mainly because it's more clear what kind of changes `MADE_CHANGES` is talking about.
- I also reordered the commands so that if writing the step output fails, the step will fail before pushing the changes. That means we'll no longer end up with half-released changes (released on GitHub but not NPM).
- Move the commitlint …

More GitHub Actions maintenance

---

.github/workflows/daily-tx-pull.yml

Call `ci-cd.yml` workflow from a job instead of a step, since GHA doesn't allow calling a workflow from a step :sweat_smile:
Also, use `git push` instead of `git push origin master` when pushing changes in the `Commit translation updates` step. When running the daily job this won't change behavior, but it does allow testing the `daily-tx-pull` workflow without contaminating the `master` branch.
Speaking of testing, check this out: https://github.com/scratchfoundation/scratch-l10n/actions/runs/6961962062
Note that the `ci-cd.yml` workflow was set up to fail early on that run to save time. The important part is that `ci-cd.yml` ran at all. Woo!

Fix workflow call
